#![no_std]
use soroban_sdk::{
    contract, contractimpl, contracttype, token, Address, Env, String, Symbol, vec, Vec
};

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    WXlmAddress,
    Maturity,
    PtBalance(Address),
    YtBalance(Address),
LastClaimRate(Address), // NEW: Checkpoint to prevent double-claiming}
}

#[contract]
pub struct PendleWrapper;

const SCALAR: i128 = 1000; // Basis points for math

#[contractimpl]
impl PendleWrapper {
    pub fn initialize(env: Env, wxlm_address: Address, maturity_timestamp: u64) {
        env.storage().persistent().set(&DataKey::WXlmAddress, &wxlm_address);
        env.storage().persistent().set(&DataKey::Maturity, &maturity_timestamp);
    }

    /// Step 1: Wrap & Split
    /// User sends 100 wXLM -> Contract gives user 100 PT and 100 YT
    pub fn mint_split(env: Env, user: Address, amount: i128) {
        user.require_auth();
        let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
        
        // 1. Pull wXLM
        token::Client::new(&env, &wxlm_addr).transfer(&user, &env.current_contract_address(), &amount);

        // 2. Set Yield Checkpoint to current rate so they don't claim past yield
        let current_rate: u64 = env.invoke_contract(&wxlm_addr, &Symbol::short("view_rate"), vec![&env]);
        env.storage().persistent().set(&DataKey::LastClaimRate(user.clone()), &current_rate);

        // 3. Update Balances
        let pt_bal = Self::get_pt_balance(env.clone(), user.clone());
        let yt_bal = Self::get_yt_balance(env.clone(), user.clone());
        env.storage().persistent().set(&DataKey::PtBalance(user.clone()), &(pt_bal + amount));
        env.storage().persistent().set(&DataKey::YtBalance(user.clone()), &(yt_bal + amount));
    }

    /// Step 2: Redeen Principal (Only after Maturity)
    /// User burns 100 PT -> Gets 100 wXLM
pub fn redeem_pt(env: Env, user: Address, amount_pt: i128) {
    user.require_auth();
    let maturity: u64 = env.storage().persistent().get(&DataKey::Maturity).unwrap_or(0);
    if env.ledger().timestamp() < maturity { panic!("Wait for maturity"); }

    let pt_bal = Self::get_pt_balance(env.clone(), user.clone());
    if pt_bal < amount_pt { panic!("Insufficient PT"); }

    // BURN PT ONLY - Leaves YT untouched
    env.storage().persistent().set(&DataKey::PtBalance(user.clone()), &(pt_bal - amount_pt));

    let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
    // Return the principal amount (not affected by yield rate)
    token::Client::new(&env, &wxlm_addr).transfer(&env.current_contract_address(), &user, &amount_pt);
}

    /// Step 3: Claim Yield (Can be called anytime)
    /// YT holder gets the "Profit" generated by the underlying wXLM
pub fn claim_yield(env: Env, user: Address) {
    user.require_auth();
    let yt_bal = Self::get_yt_balance(env.clone(), user.clone());
    if yt_bal <= 0 { panic!("No yield to claim"); }

    let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
    let current_rate: u64 = env.invoke_contract(&wxlm_addr, &Symbol::short("view_rate"), vec![&env]);
    
    // Entry rate is ALWAYS 1000 (SCALAR)
    let entry_rate: i128 = SCALAR;
    
    // Calculate TOTAL yield accumulated since minting
    // Example: 100 YT, rate is 1080 = (100 * (1080 - 1000)) / 1000 = 8 wXLM profit
    let rate_gain = (current_rate as i128) - entry_rate;
    let profit = (yt_bal * rate_gain) / SCALAR;

    // BURN ALL YT - This is a one-time claim
    env.storage().persistent().set(&DataKey::YtBalance(user.clone()), &0i128);

    if profit > 0 {
        token::Client::new(&env, &wxlm_addr).transfer(&env.current_contract_address(), &user, &profit);
        env.events().publish((Symbol::short("yield_pay"), user), profit);
    }
}

    
    pub fn combine_and_redeem(env: Env, user: Address, amount: i128) {
    user.require_auth();

    // 1. Check if user has enough of BOTH
    let pt_key = DataKey::PtBalance(user.clone());
    let yt_key = DataKey::YtBalance(user.clone());
    
    let pt_bal = env.storage().persistent().get(&pt_key).unwrap_or(0i128);
    let yt_bal = env.storage().persistent().get(&yt_key).unwrap_or(0i128);

    if pt_bal < amount || yt_bal < amount {
        panic!("You need both PT and YT to redeem early");
    }

    // 2. Burn both tokens
    env.storage().persistent().set(&pt_key, &(pt_bal - amount));
    env.storage().persistent().set(&yt_key, &(yt_bal - amount));

    // 3. Return the wXLM
    let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
    token::Client::new(&env, &wxlm_addr).transfer(&env.current_contract_address(), &user, &amount);
}

    // View functions for the UI
    pub fn get_pt_balance(env: Env, user: Address) -> i128 {
        env.storage().persistent().get(&DataKey::PtBalance(user)).unwrap_or(0)
    }

    pub fn get_yt_balance(env: Env, user: Address) -> i128 {
        env.storage().persistent().get(&DataKey::YtBalance(user)).unwrap_or(0)
    }
}