#![no_std]
use soroban_sdk::{
    contract, contractimpl, contracttype, token, Address, Env, String, Symbol, vec, Vec
};

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    WXlmAddress,
    Maturity,
    PtBalance(Address),
    YtBalance(Address),
    SavedIndex(Address), // To track how much yield YT has already claimed
}

#[contract]
pub struct PendleWrapper;

const SCALAR: i128 = 1000; // Basis points for math

#[contractimpl]
impl PendleWrapper {
    pub fn initialize(env: Env, wxlm_address: Address, maturity_timestamp: u64) {
        env.storage().persistent().set(&DataKey::WXlmAddress, &wxlm_address);
        env.storage().persistent().set(&DataKey::Maturity, &maturity_timestamp);
    }

    /// Step 1: Wrap & Split
    /// User sends 100 wXLM -> Contract gives user 100 PT and 100 YT
    pub fn mint_split(env: Env, user: Address, amount: i128) {
        user.require_auth();
        let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
        let wxlm_client = token::Client::new(&env, &wxlm_addr);

        // 1. Pull wXLM into this contract
        wxlm_client.transfer(&user, &env.current_contract_address(), &amount);

        // 2. Update PT Balance
        let pt_key = DataKey::PtBalance(user.clone());
        let current_pt = env.storage().persistent().get(&pt_key).unwrap_or(0i128);
        env.storage().persistent().set(&pt_key, &(current_pt + amount));

        // 3. Update YT Balance
        let yt_key = DataKey::YtBalance(user.clone());
        let current_yt = env.storage().persistent().get(&yt_key).unwrap_or(0i128);
        env.storage().persistent().set(&yt_key, &(current_yt + amount));
    }

    /// Step 2: Redeen Principal (Only after Maturity)
    /// User burns 100 PT -> Gets 100 wXLM
    pub fn redeem_pt(env: Env, user: Address, amount_pt: i128) {
        user.require_auth();
        let maturity: u64 = env.storage().persistent().get(&DataKey::Maturity).unwrap();
        if env.ledger().timestamp() < maturity {
            panic!("Maturity not reached yet");
        }

        let pt_key = DataKey::PtBalance(user.clone());
        let current_pt = env.storage().persistent().get(&pt_key).unwrap_or(0i128);
        if current_pt < amount_pt { panic!("Insufficient PT"); }

        // Burn PT
        env.storage().persistent().set(&pt_key, &(current_pt - amount_pt));

        // Transfer wXLM back
        let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
        let wxlm_client = token::Client::new(&env, &wxlm_addr);
        wxlm_client.transfer(&env.current_contract_address(), &user, &amount_pt);
    }

    /// Step 3: Claim Yield (Can be called anytime)
    /// YT holder gets the "Profit" generated by the underlying wXLM
    pub fn claim_yield(env: Env, user: Address) {
        user.require_auth();
        let yt_bal = env.storage().persistent().get(&DataKey::YtBalance(user.clone())).unwrap_or(0i128);
        if yt_bal == 0 { panic!("No YT owned"); }

        // Logic: In your wXLM contract, the 'rate' increases.
        // Here, we simulate claiming the difference.
        let wxlm_addr: Address = env.storage().persistent().get(&DataKey::WXlmAddress).unwrap();
        
        // We call 'view_rate' on your first contract to see how much yield was made
        // This is a cross-contract call
        let yield_rate: u64 = env.invoke_contract(&wxlm_addr, &Symbol::short("view_rate"), vec![&env]);
        
        // Profit = (YT amount * (Current Rate - 1000)) / 1000
        let profit = (yt_bal * (yield_rate as i128 - SCALAR)) / SCALAR;

        if profit > 0 {
            // In a real scenario, the YT holder gets the yield in XLM
            // For now, we assume the contract has the liquidity to pay this
            let xlm_client = token::Client::new(&env, &wxlm_addr); 
            xlm_client.transfer(&env.current_contract_address(), &user, &profit);
        }
    }

    // View functions for the UI
    pub fn get_pt_balance(env: Env, user: Address) -> i128 {
        env.storage().persistent().get(&DataKey::PtBalance(user)).unwrap_or(0)
    }

    pub fn get_yt_balance(env: Env, user: Address) -> i128 {
        env.storage().persistent().get(&DataKey::YtBalance(user)).unwrap_or(0)
    }
}